#+TITLE: Youngstown State University
#+AUTHOR: Department of Mathematics and Statistics
#+DATE: Grading Policy for STAT 5848 and 6948, Summer 2012
#+OPTIONS: toc:nil num:nil creator:nil timestamp:nil ^:nil
#+LaTeX_HEADER: \usepackage[paperwidth=8.5in,paperheight=11in]{geometry}
#+LaTeX_HEADER: \geometry{verbose,tmargin=0.5in,bmargin=1in,lmargin=1in,rmargin=1in}
#+latex: \thispagestyle{empty}

*** Contact Information:
|-----------------+---------------------------------------|
| /               | <                                     |
| *Instructor:*   | G. Jay Kerns, Ph.D.                   |
| *Office:*       | 620 Lincoln Building                  |
| *Phone No.:*    | (330) 941-3310                        |
| *E-mail:*       | [[mailto:gkerns@ysu.edu][ =gkerns@ysu.edu= ]]                    |
| *Webpage:*      | [[http://people.ysu.edu/~gkerns][ =http://people.ysu.edu/~gkerns= ]]     |
| *Office hours:* | 09:00 – 10:15 MW, or by appointment.  |
|-----------------+---------------------------------------|

*** Graded Assessments:
|----------------------------+------------|
| /                          | <          |
| Homework and Quizzes       | 100 points |
| Midterm Exam               | 200 points |
| Project                    | 120 points |
| Final Exam (comprehensive) | 300 points |
|----------------------------+------------|
| *Total Points Possible*    | 720 points |
|----------------------------+------------|
See below for a tentative exam schedule.

*** Final Grade Assignment:
|-----------+-----------+-----------+-----------+-----------|
| A         | B         | C         | D         | F         |
|-----------+-----------+-----------+-----------+-----------|
| 648 - 720 | 576 - 647 | 504 - 575 | 432 - 503 | below 432 |
|-----------+-----------+-----------+-----------+-----------|

*** Make-up policy:
- *Make-up exams* will only be given to student who misses an exam due to a documented, University sponsored event or with consent of the instructor within no more than 24 hours from the time of the absence. The student will be expected to provide verification, such as signed statement, to verify the reason for his or her absence from the exam. Any forseeable absence by the student must be discussed with the instructor in advance and arrangements made for an alternate exam at an alternate time of mutual convenience.
- *No make-up quizzes* will be given.
- *Late homework or projects* will be penalized 10% of the grade per day. 

*** Homework and projects: 
- I will specifically assign the homework problems as we go along, and at that point you will be responsible for their completion. Selected problems will be graded. You are encouraged to work ahead. If you have no clue how to solve a problem, seek out other people in the class to discuss it, and if you still are having trouble, then be sure to come and see me in my office. 
- Studying in groups is strongly encouraged. However, each student must hand in their own write-up. If you are having trouble, please see me right away. A notebook should be maintained which contains all homework exercises, properly annotated. I recommend that you work on the homework corresponding to the latest lecture. 
- Don't restrict your attention only to the assigned problems. Conceivably, items on tests may come directly from other problems in the text, so it wouldn't hurt to be familiar with them. We should have time to discuss the homework (at least briefly) at the beginning of each class and, of course, during my office hours.
- Some quizzes will be announced, some may not be.

*** Data Analysis Term Project: 
The term project can be done individually or by a team of at most four students. The term project will be graded by the following criteria: 
- Appropriateness and accuracy of analysis 60%. 
- Writing 30%: Organization 15%, Professionalism & Style 15% (see the Guide to Report Writing). 
- Thoroughness: 10%. 
Turn in your data file and the summary report file for your term project. The written report and data file due date will be announced later. Your term project report may be posted on the web in the future. If you do not wish your report to be posted by the instructor as a project report example for future students, please let me know. 

*** Attendance: 
It is expected that you will make every possible effort to attend all classes. Although I feel that it is essential for you to attend class, no direct punishment will be assessed to your final grade if you choose not to attend class. Students who miss class are responsible for finding out any pertinent information concerning the course from the instructor. 

*** Tentative schedule of exams: 
|--------------+--------------------------+---------------|
| Exam         | Date                     | Time          |
|--------------+--------------------------+---------------|
| Midterm Exam | Monday, July 23, 2012    | 14:10 – 15:15 |
| Final Exam   | Friday, Augusut 10, 2012 | 13:00 – 15:15 |
|--------------+--------------------------+---------------|

