#+TITLE:  STAT 5848/6948 | Applied Regression & Time Series
#+AUTHOR:    G. Jay Kerns
#+EMAIL:     gkerns@ysu.edu
#+DATE:      \vspace{-0.5in}
#+LANGUAGE:  en
#+OPTIONS:   H:4 author:nil toc:nil date:nil ^:nil num:nil f:nil
#+EXPORT_EXCLUDE_TAGS: answer
#+BABEL: :session *R* :results output pp :tangle yes
#+LaTeX_CLASS: article
#+LaTeX_CLASS_OPTIONS: [12pt,english]
#+LaTeX_HEADER: \usepackage[paperwidth=8.5in,paperheight=11in]{geometry}
#+LaTeX_HEADER: \geometry{verbose,tmargin=0.5in,bmargin=1in,lmargin=1in,rmargin=1in}
#+latex: \thispagestyle{empty}

The purpose of this assignment is to give you practice identifying ARIMA models.  I have generated data according to assorted ARIMA models, and your goal is to use what you have learned to identify the correct model.

* The Data: =identifyARIMA.RData=

I will send the above file to your YSU email address. It is an =R= workspace which contains five (5) generated time series, namely, =x1=, =x2=, ..., =x5=.  In order to complete the assignment, you will need to download the workspace and load it into =R= in the following way:
1. Download and save =identifyARIMA.RData= somewhere on your computer.
2. Open =RStudio=, and go to =Workspace -> Load Workspace...=.
3. Navigate to wherever it was you saved =identifyARIMA.RData= and click =Open=.
That's it.  If you type =x1= at the command prompt you should see a bunch of numbers.

* The Assignment:

\noindent
For each time series =x1=, =x2=, ..., =x5=, your goal is to identify and specify the theoretical ARIMA model that generated it.  Here are the tools at your disposal:
- Plots of the original time series and/or differences
- Lag plots of assorted orders
- Sample ACF and Sample PACF
- Extended ACF for mixed models
*For each time series* I am looking for three things:
1. The model in words, for example, AR(2).
2. The mathematical formula for your model.  For example, an AR(2) model with mean zero looks like this:
   \begin{equation}
   Y_{t} = \phi_{1}Y_{t - 1} + \phi_{2}Y_{t - 2} + e_{t}
   \end{equation}
   You can get this formula in your =Sweave= report with the following code:
   : \begin{equation}
   : Y_{t} = \phi_{1}Y_{t - 1} + \phi_{2}Y_{t - 2} + e_{t}
   : \end{equation}
3. Any supporting arguments, work, and/or plots you used to come to your conclusion.
* Assignment Deliverables:
Email your =Sweave=  =.Rnw= file to me at =gkerns@ysu.edu= by the due date, *Monday, July 23, 2012 @ 13:00*.  (Early submission is encouraged.)

* Hints:
- Try figuring out =x5= first.
- It is not necessary to transform any of the data with =sqrt=, =log=, etc.
- To take the first difference $\nabla X_{t}$ do =diff(x)=.  To take the second difference  $\nabla^{2} X_{t}$ do =diff(diff(x))= or =diff(x, differences = 2)=, and so forth.
- The $\LaTeX$ code for $\theta$, $\mu$, /etc./ is =\theta=, =\mu=, /etc./  The code for $\nabla$ and  $\nabla^{2}$ is =\nabla= and =\nabla^{2}=.

* Making your report look pretty:
The more comfortable you get working with =Sweave= files and $\LaTeX$, the more professionalism I am going to expect out of your reports.  For instance, for this assignment, everybody should have at bare minimum a title, author, and clearly delineated problems.

Everybody should have the following line somewhere in their report (above the =\begin{document}= line, preferably).
: \title{Identifying ARIMA Models Assignment}

The report should also say who wrote it, with a line somewhere that says something like this:
: \author{Sir Ronald Aylmer Fisher}

You can divide your report up into sections, say, with different sections addressed to different problems.  For instance, you could do something like this:
: \section{The simulated time series \texttt{x1}}
:
: Here are a bunch of code chunks and plots about \texttt{x1}.
:
:
: \section{The simulated time series \texttt{x2}}
:
: Here are a bunch of code chunks and plots about \texttt{x2}.
:
: And so forth...

Some of you are pretty good with $\LaTeX$ already and do not need additional guidance;  make your report as professional as you would anyway.
